' <auto-generated />
Imports System
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports Microsoft.VisualBasic
Imports Npgsql.EntityFrameworkCore.PostgreSQL.Metadata
Imports TheaterTicketingSystem

Namespace Global.TheaterTicketingSystem.Migrations
    <DbContext(GetType(TheaterContext))>
    <Migration("20260221163251_init")>
    Partial Class init
        ''' <inheritdoc />
        Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
            modelBuilder.
                HasAnnotation("ProductVersion", "8.0.24").
                HasAnnotation("Relational:MaxIdentifierLength", 63)

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder)

            modelBuilder.Entity("TheaterTicketingSystem.Booking",
                Sub(b)
                    b.Property(Of Integer)("Id").
                        ValueGeneratedOnAdd().
                        HasColumnType("integer")

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property(Of Integer)("Id"))

                    b.Property(Of Date)("CreatedAt").
                        HasColumnType("timestamp without time zone")

                    b.Property(Of String)("CustomerName").
                        IsRequired().
                        HasColumnType("text")

                    b.Property(Of Boolean)("IsDeleted").
                        HasColumnType("boolean")

                    b.Property(Of Integer)("PerformanceId").
                        HasColumnType("integer")

                    b.Property(Of String)("PhoneNumber").
                        IsRequired().
                        HasMaxLength(20).
                        HasColumnType("character varying(20)")

                    b.Property(Of Integer)("Quantity").
                        HasColumnType("integer")

                    b.Property(Of Integer)("SeatType").
                        HasColumnType("integer")

                    b.Property(Of Decimal)("TotalPrice").
                        HasColumnType("numeric")

                    b.Property(Of Decimal)("UnitPrice").
                        HasColumnType("numeric")

                    b.Property(Of Date?)("UpdatedAt").
                        HasColumnType("timestamp without time zone")

                    b.HasKey("Id")

                    b.HasIndex("PerformanceId")

                    b.ToTable("Bookings")
                End Sub)

            modelBuilder.Entity("TheaterTicketingSystem.Performance",
                Sub(b)
                    b.Property(Of Integer)("Id").
                        ValueGeneratedOnAdd().
                        HasColumnType("integer")

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property(Of Integer)("Id"))

                    b.Property(Of Date)("CreatedAt").
                        HasColumnType("timestamp without time zone")

                    b.Property(Of Integer)("Duration").
                        HasColumnType("integer")

                    b.Property(Of Boolean)("IsDeleted").
                        HasColumnType("boolean")

                    b.Property(Of String)("Name").
                        IsRequired().
                        HasColumnType("text")

                    b.Property(Of Date)("StartTime").
                        HasColumnType("timestamp without time zone")

                    b.Property(Of Date?)("UpdatedAt").
                        HasColumnType("timestamp without time zone")

                    b.HasKey("Id")

                    b.ToTable("Performances")
                End Sub)

            modelBuilder.Entity("TheaterTicketingSystem.SeatAssignment",
                Sub(b)
                    b.Property(Of Integer)("Id").
                        ValueGeneratedOnAdd().
                        HasColumnType("integer")

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property(Of Integer)("Id"))

                    b.Property(Of Integer)("BookingId").
                        HasColumnType("integer")

                    b.Property(Of Date)("CreatedAt").
                        HasColumnType("timestamp without time zone")

                    b.Property(Of Boolean)("IsDeleted").
                        HasColumnType("boolean")

                    b.Property(Of Integer)("Number").
                        HasColumnType("integer")

                    b.Property(Of Integer)("PerformanceId").
                        HasColumnType("integer")

                    b.Property(Of String)("Row").
                        HasColumnType("text")

                    b.Property(Of Date?)("UpdatedAt").
                        HasColumnType("timestamp without time zone")

                    b.HasKey("Id")

                    b.HasIndex("BookingId")

                    b.HasIndex("PerformanceId")

                    b.ToTable("SeatAssignments")
                End Sub)

            modelBuilder.Entity("TheaterTicketingSystem.Booking",
                Sub(b)
                    b.HasOne("TheaterTicketingSystem.Performance", "Performance").
                        WithMany().
                        HasForeignKey("PerformanceId").
                        OnDelete(DeleteBehavior.Cascade).
                        IsRequired()
                    b.Navigation("Performance")
                End Sub)

            modelBuilder.Entity("TheaterTicketingSystem.SeatAssignment",
                Sub(b)
                    b.HasOne("TheaterTicketingSystem.Booking", "Booking").
                        WithMany("SeatAssignments").
                        HasForeignKey("BookingId").
                        OnDelete(DeleteBehavior.Cascade).
                        IsRequired()

                    b.HasOne("TheaterTicketingSystem.Performance", "Performance").
                        WithMany().
                        HasForeignKey("PerformanceId").
                        OnDelete(DeleteBehavior.Cascade).
                        IsRequired()
                    b.Navigation("Booking")

                    b.Navigation("Performance")
                End Sub)

            modelBuilder.Entity("TheaterTicketingSystem.Booking",
                Sub(b)
                    b.Navigation("SeatAssignments")
                End Sub)
        End Sub
    End Class
End Namespace
